/**
 * Created by hlwen on 2017/1/1.
 */
/* Automatic generated by './build/bin/build-entry.js' */

import Grid from './Grid.vue';
import SelectTree from './SelectTree.vue';

const install = function(Vue) {
    /* istanbul ignore if */
    if (install.installed) return;

    Vue.component(Grid.name, Grid);
    Vue.component(SelectTree.name, SelectTree);

    // Vue.use(Loading.directive);

    // Vue.prototype.$loading = Loading.service;
    // Vue.prototype.$msgbox = MessageBox;
    // Vue.prototype.$alert = MessageBox.alert;
    // Vue.prototype.$confirm = MessageBox.confirm;
    // Vue.prototype.$prompt = MessageBox.prompt;
    // Vue.prototype.$notify = Notification;
    // Vue.prototype.$message = Message;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
};

module.exports = {
    version: '0.0.1',
    install,
    Grid,
    SelectTree
};
